baseURL: "https://blog.mmswe.com/"
title: "Myanmar Software Engineers | Blog"
paginate: 20
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-ZRCJBC23GB

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "Myanmar Software Engineers | Blog"
  description: "A collection of Myanmar Software Engineers' articles"
  keywords: [Blog, Portfolio, myanmar, software]
  author: "Myanmar Software Engineers"
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2024"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: true
  showtoc: false
  tocopen: false

  assets:
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: " MMSWE Blog"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: "Myanmar Software Engineers | Blog"
    subtitle: "Profile"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Myanmar Software Engineers | Blog"
    Content: "မြန်မာ Software Engineer များရေးသားထားသော နည်းပညာဆောင်းပါးများ"

  socialIcons:
    - name: facebook
      url: "https://facebook.com/groups/myanmarsoftwareengineers"
    - name: github
      url: "https://github.com/myanmar-software-engineers"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai